export enum KafkaClientEnvironment {
  KAFKA_SERVICE_NAME = 'KAFKA_SERVICE_NAME',
  KAFKA_PORT = 'KAFKA_PORT',
  KAFKA_CONNECTION_RETRIES = 'KAFKA_CONNECTION_RETRIES',
  KAFKA_CONSUMER_GROUP_ID = 'KAFKA_CONSUMER_GROUP',
}
