name: CI
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm i --ignore-scripts --no-audit --no-fund # Install without scripts
      - run: npm rebuild && npm run prepare --if-present # Run scripts here to prevent access to NODE_AUTH_TOKEN
      - run: npx nx affected --target=test --parallel=2
      - run: npx nx affected --target=build --parallel=2
      - run: npx nx affected --target=docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
